# Generated by Django 6.0.6 on 2026-09-05 08:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0002_appassistantquestion'),
    ]

    operations = [
        migrations.CreateModel(
            name='AliasMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier_type', models.CharField(choices=[('IP', 'IP address'), ('HOST', 'Hostname'), ('DOMAIN', 'Domain'), ('EMAIL', 'Email address'), ('USER', 'Username/account'), ('ORG', 'Organization name'), ('PERSON', 'Person name'), ('PATH', 'File path')], max_length=20)),
                ('normalized_value', models.CharField(max_length=512)),
                ('real_value', models.CharField(max_length=512)),
                ('sequence', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_seen_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alias_mappings', to='organizations.organization')),
            ],
            options={
                'indexes': [models.Index(fields=['organization', 'identifier_type', 'normalized_value'], name='aliasmapping_lookup_idx')],
                'constraints': [models.UniqueConstraint(fields=('organization', 'identifier_type', 'normalized_value'), name='uniq_alias_per_org_type_value'), models.UniqueConstraint(fields=('organization', 'identifier_type', 'sequence'), name='uniq_alias_sequence_per_org_type')],
            },
        ),
    ]
