# Generated by Django 6.0.6 on 2026-08-25 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playbooks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='playbookstep',
            name='source',
            field=models.CharField(choices=[('generic', 'Generic'), ('ai_generated', 'AI Generated')], default='generic', max_length=20),
        ),
    ]
