# Generated by Django 6.0.6 on 2026-08-28 09:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0007_incidentexplanation'),
        ('playbooks', '0002_playbookstep_source'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChecklistItemState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_key', models.CharField(max_length=300)),
                ('is_completed', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('checklist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_states', to='playbooks.sopchecklist')),
                ('incident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checklist_item_states', to='incidents.incidentgroup')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('incident', 'checklist', 'item_key'), name='unique_checklist_item_state_per_incident')],
            },
        ),
    ]
