# Generated by Django 5.0.6 on 2026-06-21 11:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('incidents', '0001_initial'),
        ('organizations', '0001_initial'),
        ('risk', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DisasterReadinessFinding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('readiness_issue', models.CharField(max_length=255)),
                ('disaster_impact', models.TextField()),
                ('recovery_concern', models.TextField()),
                ('source', models.CharField(choices=[('log_based', 'Log Based'), ('user_based', 'User Based'), ('manual', 'Manual')], default='log_based', max_length=20)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('incident', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='readiness_findings', to='incidents.incidentgroup')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='readiness_findings', to='organizations.organization')),
                ('risk', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='readiness_findings', to='risk.riskassessment')),
            ],
        ),
        migrations.CreateModel(
            name='ReadinessPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scenario', models.CharField(max_length=255)),
                ('checklist', models.TextField(blank=True)),
                ('questions', models.TextField(blank=True)),
                ('recommended_actions', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='readiness_plans', to='organizations.organization')),
            ],
        ),
    ]
