# Generated by Django 6.0.6 on 2026-08-30 00:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0001_initial'),
        ('resilience', '0004_readinessquestion'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReadinessScoreSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.PositiveSmallIntegerField()),
                ('computed_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='readiness_score_snapshots', to='organizations.organization')),
            ],
            options={
                'ordering': ['computed_at'],
            },
        ),
    ]
