# Generated by Django 6.0.6 on 2026-09-03 00:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('endpoints', '0002_endpoint_token_hash'),
        ('incidents', '0011_incidentgroup_assigned_to'),
        ('organizations', '0002_appassistantquestion'),
    ]

    operations = [
        migrations.AddField(
            model_name='endpointevent',
            name='correlation_scanned_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.CreateModel(
            name='EndpointCorrelationCandidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_event_at', models.DateTimeField()),
                ('last_event_at', models.DateTimeField()),
                ('event_count', models.PositiveIntegerField(default=0)),
                ('trigger_summary', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pending triage'), ('escalated', 'Escalated to incident'), ('benign', 'Triaged - not worth attention'), ('triage_failed', 'Triage call failed'), ('rate_limited', 'Triage rate-limited'), ('abandoned', 'Triage abandoned - manual check required')], db_index=True, default='pending', max_length=20)),
                ('attempt_count', models.PositiveIntegerField(default=0)),
                ('ai_verdict', models.CharField(blank=True, choices=[('escalate', 'Escalate'), ('benign', 'Benign')], max_length=10)),
                ('ai_severity', models.CharField(blank=True, choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], max_length=10)),
                ('ai_summary', models.TextField(blank=True)),
                ('ai_reasoning', models.TextField(blank=True)),
                ('ai_model', models.CharField(blank=True, max_length=100)),
                ('ai_error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('triaged_at', models.DateTimeField(blank=True, null=True)),
                ('endpoint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='correlation_candidates', to='endpoints.endpoint')),
                ('incident', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='endpoint_correlation_candidates', to='incidents.incidentgroup')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='endpoint_correlation_candidates', to='organizations.organization')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='endpointevent',
            name='candidate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='endpoints.endpointcorrelationcandidate'),
        ),
    ]
