# Generated by Django 6.0.6 on 2026-08-31 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0001_initial'),
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='airun',
            index=models.Index(fields=['-created_at'], name='airun_created_at_desc_idx'),
        ),
    ]
