# Generated by Django 5.0.6 on 2026-06-21 11:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadedLogFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=255)),
                ('source_type', models.CharField(choices=[('wazuh', 'Wazuh'), ('graylog', 'Graylog'), ('prtg', 'PRTG'), ('proxmox', 'Proxmox'), ('firewall', 'Firewall'), ('backup', 'Backup'), ('ssl_certificate', 'SSL Certificate'), ('windows', 'Windows'), ('linux', 'Linux'), ('other', 'Other')], default='other', max_length=30)),
                ('storage_path', models.CharField(max_length=500)),
                ('status', models.CharField(choices=[('uploaded', 'Uploaded'), ('parsing', 'Parsing'), ('parsed', 'Parsed'), ('failed', 'Failed')], default='uploaded', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_logs', to='organizations.organization')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_log_files', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ParsedAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_tool', models.CharField(max_length=100)),
                ('timestamp', models.DateTimeField(blank=True, null=True)),
                ('affected_system', models.CharField(blank=True, max_length=255)),
                ('account', models.CharField(blank=True, max_length=255)),
                ('source_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('destination_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('event_type', models.CharField(max_length=255)),
                ('severity_hint', models.CharField(choices=[('unknown', 'Unknown'), ('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='unknown', max_length=20)),
                ('raw_message', models.TextField(blank=True)),
                ('normalized_summary', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parsed_alerts', to='organizations.organization')),
                ('uploaded_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parsed_alerts', to='log_intake.uploadedlogfile')),
            ],
        ),
    ]
