# Generated by Django 6.0.6 on 2026-08-20 23:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log_intake', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='parsedalert',
            name='confidence_score',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)]),
        ),
    ]
