# Generated by Django 6.0.6 on 2026-08-26 00:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('risk', '0002_alter_riskassessment_impact_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RiskNarration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('narration_text', models.TextField()),
                ('model_used', models.CharField(blank=True, max_length=100)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('gap', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='risk_narrations', to='risk.gapfinding')),
            ],
            options={
                'ordering': ['-generated_at'],
            },
        ),
    ]
