# Generated by Django 6.0.6 on 2026-08-26 09:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('risk', '0003_risknarration'),
    ]

    operations = [
        migrations.CreateModel(
            name='RiskQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField()),
                ('answer_text', models.TextField()),
                ('model_used', models.CharField(blank=True, max_length=100)),
                ('asked_at', models.DateTimeField(auto_now_add=True)),
                ('gap', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='risk_questions', to='risk.gapfinding')),
            ],
            options={
                'ordering': ['asked_at'],
            },
        ),
    ]
