# Generated by Django 6.0.6 on 2026-09-01 08:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppAssistantQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField()),
                ('answer_text', models.TextField()),
                ('model_used', models.CharField(blank=True, max_length=100)),
                ('asked_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='app_assistant_questions', to='organizations.organization')),
            ],
            options={
                'ordering': ['asked_at'],
            },
        ),
    ]
