# Generated by Django 6.0.6 on 2026-08-25 08:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0002_incidentgroup_confidence'),
        ('log_intake', '0002_parsedalert_confidence_score'),
    ]

    operations = [
        migrations.CreateModel(
            name='IncidentSourceIPLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_ip', models.GenericIPAddressField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('incident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source_ip_links', to='incidents.incidentgroup')),
                ('matched_alert', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='log_intake.parsedalert')),
                ('related_incident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source_ip_linked_from', to='incidents.incidentgroup')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('incident', 'related_incident', 'source_ip'), name='unique_incident_source_ip_link')],
            },
        ),
    ]
