# Generated by Django 6.0.6 on 2026-08-25 10:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0003_incidentsourceiplink'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalystResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('analysis_text', models.TextField()),
                ('model_used', models.CharField(blank=True, max_length=100)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('incident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analyst_results', to='incidents.incidentgroup')),
            ],
            options={
                'ordering': ['-generated_at'],
            },
        ),
    ]
