# Generated by Django 6.0.6 on 2026-08-25 22:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0004_analystresult'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalystQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField()),
                ('answer_text', models.TextField()),
                ('model_used', models.CharField(blank=True, max_length=100)),
                ('asked_at', models.DateTimeField(auto_now_add=True)),
                ('incident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analyst_questions', to='incidents.incidentgroup')),
            ],
            options={
                'ordering': ['asked_at'],
            },
        ),
    ]
