# Generated by Django 6.0.6 on 2026-08-26 09:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0005_analystquestion'),
    ]

    operations = [
        migrations.CreateModel(
            name='IncidentComparison',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comparison_text', models.TextField()),
                ('model_used', models.CharField(blank=True, max_length=100)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('compared_incident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comparisons_targeting_here', to='incidents.incidentgroup')),
                ('incident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comparisons_started_here', to='incidents.incidentgroup')),
            ],
            options={
                'ordering': ['generated_at'],
            },
        ),
    ]
