# Generated by Django 6.0.6 on 2026-08-26 09:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0006_incidentcomparison'),
    ]

    operations = [
        migrations.CreateModel(
            name='IncidentExplanation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audience', models.CharField(choices=[('plain_language', 'Plain Language'), ('management', 'What To Tell Management')], max_length=20)),
                ('explanation_text', models.TextField()),
                ('model_used', models.CharField(blank=True, max_length=100)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('incident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='explanations', to='incidents.incidentgroup')),
            ],
            options={
                'ordering': ['-generated_at'],
            },
        ),
    ]
