# Generated by Django 6.0.6 on 2026-08-29 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0007_incidentexplanation'),
    ]

    operations = [
        migrations.AddField(
            model_name='incidentgroup',
            name='workflow_state',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
