# Generated by Django 6.0.6 on 2026-08-30 00:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0009_workflowstepguidance_workflowstepquestion'),
    ]

    operations = [
        migrations.CreateModel(
            name='VerificationItemEvidenceState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_key', models.CharField(max_length=50)),
                ('tier', models.CharField(choices=[('evidence_available', 'Evidence Available'), ('manual_check_required', 'Manual Check Required')], max_length=30)),
                ('evidence_summary', models.TextField(blank=True)),
                ('computed_at', models.DateTimeField(auto_now=True)),
                ('incident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verification_evidence_states', to='incidents.incidentgroup')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('incident', 'item_key'), name='unique_incident_verification_item_state')],
            },
        ),
    ]
